
/* Automatically generated by './build/build-entry.js' */

import Button from '../packages/button'
import Toast from '../packages/toast'
import MessageBox from '../packages/message-box'
import Lazyload from '../packages/lazyload'
import locale from './locale'

const components = [
  Button,
  MessageBox.wdMessageBox
]

const install = (Vue, config = {}) => {
  locale.use(config.locale)
  locale.i18n(config.i18n)

  components.forEach(component => {
    Vue.component(component.name, component)
  })

  Vue.prototype.$toast = Toast
  Vue.prototype.$messageBox = MessageBox.MessageBox

  Vue.use(Lazyload, config.lazyload)
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.5.1',
  install,
  locale: locale.use,
  i18n: locale.i18n,
  Button,
  Toast,
  MessageBox,
  Lazyload
}
